### ISSUE TITLE
Add name attribute to `logrel-mltt.agda-lib` file

### ISSUE THREAD

**Issue by brunorochapaiva** [mr-ohman/logrel-mltt#10]
Currently `logrel-mltt.agda-lib` looks like
```
depend: standard-library
include: .
```
so it is missing a name attribute which makes it impossible to use this work as a library in a separate formalisation. Adding a name attribute would fix this, such as
```
name: logrel-mltt
depend: standard-library
include: .
```

**Comment by mr-ohman** [comment]
Thank you for pointing this out! I will go ahead and fix this.
