### ISSUE TITLE
Add continuous integration (CI)

### ISSUE THREAD

**Issue by andreasabel** [mr-ohman/logrel-mltt#9]
We should consider setting up a CI that checks PRs and maybe branches (upon trigger) with one or several versions of Agda.
I don't have any experience with CI for Agda developments yet, but one could research existing solutions:
- https://doisinkidney.com/posts/2020-11-18-agda-github-action.html
- https://github.com/UniMath/agda-unimath/blob/6861f6ec44417f4a9cc4c320b250468f31532afd/.github/workflows/ci.yaml
- ... (please suggest more resources)

**Comment by gallais** [comment]
The stdlib's CI is here: https://github.com/agda/agda-stdlib/blob/master/.github/workflows/ci-ubuntu.yml
